name: NewsAutodoc

options:
  deploymentTarget:
    iOS: 14.0
  minimumXcodeGenVersion: 2.6.0
  bundleIdPrefix: com.dmmolod.NewsAutodoc

fileGroups:
  - SupportingFiles

settingGroups:
  application:
    FRAMEWORK_SEARCH_PATHS: $(inherited)
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    INFOPLIST_FILE: SupportingFiles/Info.plist
    SWIFT_VERSION: "5.7"
    TARGETED_DEVICE_FAMILY: "1,2"
    PRODUCT_BUNDLE_IDENTIFIER: com.dmmolod.NewsAutodoc
    OTHER_LDFLAGS: $(inherited) "-ObjC"

targetTemplates:       
  main_application:
    platform: iOS
    type: application
    scheme: {}
    sources:
      - App
      - Api
      - Generals
      - Screens
      - Services

targets:
# APP
  Appstore:
    templates:
      - main_application
    settings:
      base:
        PRODUCT_NAME: Autodoc News
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) APPSTORE
      groups:
        - application
